FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

COPY . .

RUN dotnet restore

RUN dotnet publish \
src/VaccinationCard.Api \
-c Release \
-o /app

WORKDIR /app

ENTRYPOINT [
"dotnet",
"VaccinationCard.Api.dll"
]